# Generated by Django 3.1.6 on 2021-02-26 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210224_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.cartstatus'),
        ),
    ]
